english_pretexts = {
    '': True,
    'a': True,
    'an': True,
    'the': True,
    'in': True,
    'at': True,
    'to': True,
    'on': True,
    'for': True,
    'of': True,
    'by': True,
    's': True,
    'is': True,
    'and': True,
    'with': True,
    'or': True,
}
